[package]
name = "pheasant_uri"
version = "0.1.0"
edition = "2024"

# [[test]]
# name = "basic"
# path = "tests/basic.rs"

[[test]]
name = "lex"
path = "tests/lex.rs"

[[bin]]
name = "dev"
path = "src/main.rs"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
syn = { version = "2.0.104", features = ["printing", "full", "parsing", "extra-traits"] }
